# Validate the sample data
SELECT * FROM customer_behavior.customers_data limit 5;

# What is the total revenue generated by male & Female customers
select gender, sum(purchase_amount) Revenue
from 
customer_behavior.customers_data
group by gender;

# Which customers used discount but still spent more than the average purchase amount?
select customer_id,purchase_amount
from
customer_behavior.customers_data
where discount_applied='Yes'
and purchase_amount >= (select avg(purchase_amount) from customer_behavior.customers_data);

# Which are the top 5 products with respect to higest average review_ratings
select item_purchased, round(avg(review_rating),2) as avg_rating
from 
customer_behavior.customers_data
group by item_purchased
order by avg(review_rating) desc
limit 5;

# compare the average purchase amounts between standard and express shipping
select round(avg(purchase_amount),2) avg_purchase_amount,shipping_type
from 
customer_behavior.customers_data
where shipping_type in ('Express','Standard')
Group by shipping_type;

# Do subscribed customers spend more? compare avg spend and total revenue between subscribers and non-subscribers
select subscription_status,
count(customer_id) count,
round(avg(purchase_amount),2) avg_spend,
round(sum(purchase_amount),2) total_revenue
from
customer_behavior.customers_data
group by subscription_status;

# which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round((sum(case when discount_applied='Yes' then 1 else 0 end)/count(*))*100,2) as discount_rate
from  
customer_behavior.customers_data
group by item_purchased
order by discount_rate desc
limit 5;

# Segment customers into New, Returning and loyal based on their total no of previous purchases and show 
# count of each segment

with customer_segment as (
select 
customer_id, previous_purchases,
case 
when previous_purchases=1 then 'New'
when previous_purchases >1 and previous_purchases<20  then 'Returning'
Else 'Loyal'
end as csegment
from
customer_behavior.customers_data)

select  csegment as customer_segment,
count(*) as cnt
from customer_segment
group by csegment;

# What are top 3 most purchased products against each category
with item_cnts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rnk
from 
customer_behavior.customers_data
group by 
category,
item_purchased
)

select 
item_rnk,
category,
item_purchased,
total_orders
from 
item_cnts
where item_rnk<=3;